import type { Metadata } from "next";
import { notFound, redirect } from "next/navigation";

import { PreviewReport } from "@/components/report/PreviewReport";
import { ScanPending } from "@/components/scan/ScanPending";
import { exampleReport } from "@/lib/report/example";
import { hasEntitlement } from "@/lib/payments/entitlements";
import { toPreviewDoc } from "@/lib/report/preview";
import { getReportByScan, getScanStatus, isUuid } from "@/lib/scans/repository";

export const dynamic = "force-dynamic";

// Dynamic unfurl text so a shared scan link reads "<domain> scored 75/100 …".
// The card image itself is generated by opengraph-image.tsx in this segment.
export async function generateMetadata({
  params,
}: {
  params: Promise<{ id: string }>;
}): Promise<Metadata> {
  const { id } = await params;
  const report = id === "demo" ? exampleReport : isUuid(id) ? await getReportByScan(id) : null;
  if (!report) {
    return { title: "AI Search Readiness scan", twitter: { card: "summary_large_image" } };
  }
  const score = Math.round(report.overall_score);
  const domain = report.meta.canonical_domain;
  return {
    title: `${domain} scored ${score}/100 for AI search readiness`,
    description: `See how ready ${domain} is to be found, trusted and cited by ChatGPT, Perplexity and Gemini — and exactly what to fix.`,
    twitter: { card: "summary_large_image" },
  };
}

// E12 Free Preview — renders the free-preview projection of the stored report
// (premium fields stripped server-side), or a live progress view while the scan
// runs. `demo` shows the example fixture.
export default async function ScanPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  if (id === "demo") return <PreviewReport preview={toPreviewDoc(exampleReport)} reportId="demo" />;
  if (!isUuid(id)) notFound();

  const report = await getReportByScan(id);
  if (report) {
    // Already unlocked (paid or promo) — show the full report, not the paywall.
    // This also catches a webhook that granted the entitlement after checkout.
    if (await hasEntitlement(id)) redirect(`/report/${id}`);
    return <PreviewReport preview={toPreviewDoc(report)} reportId={id} />;
  }

  const status = await getScanStatus(id);
  if (!status) notFound();
  return <ScanPending scanId={id} status={status.status} />;
}
