// The example report the demo pages render, generated by the worker
// (apps/worker/scripts/gen_example_report.py). Until live scans are wired
// through the API, E12/E13 render this fixture.
import data from "./example-report.json";
import type { ReportDocument } from "./types";

export const exampleReport = data as unknown as ReportDocument;
