"""v2 readiness snapshot fields

Revision ID: aaa69085a4a2
Revises: f1e9b133848e
Create Date: 2026-08-20 07:17:58.670907+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aaa69085a4a2"
down_revision: str | None = "f1e9b133848e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "readiness_snapshots",
        sa.Column("retrieval_readiness_score", sa.Numeric(precision=6, scale=2), nullable=True),
    )
    op.add_column(
        "readiness_snapshots",
        sa.Column("citation_readiness_score", sa.Numeric(precision=6, scale=2), nullable=True),
    )
    op.add_column(
        "readiness_snapshots",
        sa.Column("answer_extractability_score", sa.Numeric(precision=6, scale=2), nullable=True),
    )
    op.add_column(
        "readiness_snapshots", sa.Column("methodology_hash", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "readiness_snapshots",
        sa.Column("measurement_as_of", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("readiness_snapshots", "measurement_as_of")
    op.drop_column("readiness_snapshots", "methodology_hash")
    op.drop_column("readiness_snapshots", "answer_extractability_score")
    op.drop_column("readiness_snapshots", "citation_readiness_score")
    op.drop_column("readiness_snapshots", "retrieval_readiness_score")
    # ### end Alembic commands ###
