"""initial schema

Revision ID: c5217703c6c7
Revises:
Create Date: 2026-08-19 08:51:21.865795+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c5217703c6c7"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jobs",
        sa.Column(
            "job_type",
            sa.Enum(
                "crawl_project",
                "parse_page",
                "build_profile",
                "generate_clusters",
                "compute_coverage",
                "compute_readiness",
                "generate_actions",
                "build_report",
                name="job_type",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("payload_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "leased",
                "running",
                "succeeded",
                "retry_wait",
                "failed",
                "dead",
                "cancelled",
                name="job_status",
                native_enum=False,
                length=32,
            ),
            server_default="queued",
            nullable=False,
        ),
        sa.Column("priority", sa.Integer(), server_default="0", nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("attempt", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_attempts", sa.Integer(), server_default="5", nullable=False),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("worker_id", sa.String(length=128), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_detail_redacted", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_jobs_idempotency_key")),
    )
    op.create_index(op.f("ix_jobs_available_at"), "jobs", ["available_at"], unique=False)
    op.create_index(op.f("ix_jobs_status"), "jobs", ["status"], unique=False)
    op.create_table(
        "stripe_events",
        sa.Column("stripe_event_id", sa.String(length=255), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stripe_events")),
        sa.UniqueConstraint("stripe_event_id", name=op.f("uq_stripe_events_stripe_event_id")),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "active", "disabled", name="user_status", native_enum=False, length=32
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("owner_user_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_organizations_owner_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
    )
    op.create_index(
        op.f("ix_organizations_owner_user_id"), "organizations", ["owner_user_id"], unique=False
    )
    op.create_table(
        "projects",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("canonical_domain", sa.String(length=255), nullable=False),
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.Column("locale", sa.String(length=16), nullable=True),
        sa.Column(
            "status",
            sa.Enum("active", "archived", name="project_status", native_enum=False, length=32),
            server_default="active",
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_projects_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
        sa.UniqueConstraint(
            "organization_id",
            "canonical_domain",
            name=op.f("uq_projects_organization_id_canonical_domain"),
        ),
    )
    op.create_index(
        op.f("ix_projects_organization_id"), "projects", ["organization_id"], unique=False
    )
    op.create_table(
        "scans",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column(
            "scan_type",
            sa.Enum("quick", "full", name="scan_type", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("methodology_version", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "created",
                "queued",
                "crawling",
                "extracting",
                "profiling",
                "clustering",
                "coverage",
                "scoring",
                "actions",
                "report",
                "completed",
                "partial",
                "failed",
                "cancelled",
                name="scan_status",
                native_enum=False,
                length=32,
            ),
            server_default="created",
            nullable=False,
        ),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("max_pages", sa.Integer(), nullable=False),
        sa.Column("max_browser_renders", sa.Integer(), nullable=False),
        sa.Column("page_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("browser_render_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_scans_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scans")),
    )
    op.create_index(op.f("ix_scans_project_id"), "scans", ["project_id"], unique=False)
    op.create_table(
        "actions",
        sa.Column("scan_id", sa.UUID(), nullable=False),
        sa.Column("rule_id", sa.String(length=32), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column(
            "severity",
            sa.Enum(
                "low",
                "medium",
                "high",
                "critical",
                name="action_severity",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("priority_score", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("problem", sa.Text(), nullable=True),
        sa.Column("evidence_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("recommendation", sa.Text(), nullable=True),
        sa.Column("expected_signal", sa.Text(), nullable=True),
        sa.Column("measurement_hint", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "acknowledged",
                "resolved",
                "dismissed",
                name="action_status",
                native_enum=False,
                length=32,
            ),
            server_default="open",
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["scan_id"], ["scans.id"], name=op.f("fk_actions_scan_id_scans"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_actions")),
    )
    op.create_index(op.f("ix_actions_scan_id"), "actions", ["scan_id"], unique=False)
    op.create_table(
        "business_profiles",
        sa.Column("scan_id", sa.UUID(), nullable=False),
        sa.Column("legal_name", sa.String(length=255), nullable=True),
        sa.Column("brand_name", sa.String(length=255), nullable=True),
        sa.Column("canonical_domain", sa.String(length=255), nullable=True),
        sa.Column("aliases_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("products_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("services_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("locations_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("countries_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("languages_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("industries_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("target_audiences_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("evidence_summary_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("profile_hash", sa.String(length=64), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["scan_id"],
            ["scans.id"],
            name=op.f("fk_business_profiles_scan_id_scans"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_business_profiles")),
        sa.UniqueConstraint("scan_id", name=op.f("uq_business_profiles_scan_id")),
    )
    op.create_index(
        op.f("ix_business_profiles_profile_hash"),
        "business_profiles",
        ["profile_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_business_profiles_scan_id"), "business_profiles", ["scan_id"], unique=False
    )
    op.create_table(
        "crawl_pages",
        sa.Column("scan_id", sa.UUID(), nullable=False),
        sa.Column("normalized_url", sa.Text(), nullable=False),
        sa.Column("final_url", sa.Text(), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("content_type", sa.String(length=128), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("meta_description", sa.Text(), nullable=True),
        sa.Column("canonical_url", sa.Text(), nullable=True),
        sa.Column("robots_meta", sa.String(length=255), nullable=True),
        sa.Column("language", sa.String(length=16), nullable=True),
        sa.Column("h1", sa.Text(), nullable=True),
        sa.Column("headings_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("visible_text", sa.Text(), nullable=True),
        sa.Column("json_ld_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("internal_links_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("external_links_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("render_method", sa.String(length=16), nullable=True),
        sa.Column("fetch_duration_ms", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["scan_id"], ["scans.id"], name=op.f("fk_crawl_pages_scan_id_scans"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_crawl_pages")),
    )
    op.create_index(
        op.f("ix_crawl_pages_content_hash"), "crawl_pages", ["content_hash"], unique=False
    )
    op.create_index(op.f("ix_crawl_pages_scan_id"), "crawl_pages", ["scan_id"], unique=False)
    op.create_table(
        "payments",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("scan_id", sa.UUID(), nullable=True),
        sa.Column("provider", sa.String(length=32), server_default="stripe", nullable=False),
        sa.Column("stripe_customer_id", sa.String(length=255), nullable=True),
        sa.Column("stripe_checkout_session_id", sa.String(length=255), nullable=True),
        sa.Column("stripe_payment_intent_id", sa.String(length=255), nullable=True),
        sa.Column("product_code", sa.String(length=64), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "paid",
                "failed",
                "expired",
                "refunded",
                name="payment_status",
                native_enum=False,
                length=32,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("refunded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_payments_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_payments_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["scan_id"], ["scans.id"], name=op.f("fk_payments_scan_id_scans"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
        sa.UniqueConstraint(
            "stripe_checkout_session_id", name=op.f("uq_payments_stripe_checkout_session_id")
        ),
    )
    op.create_index(
        op.f("ix_payments_organization_id"), "payments", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_payments_project_id"), "payments", ["project_id"], unique=False)
    op.create_index(op.f("ix_payments_scan_id"), "payments", ["scan_id"], unique=False)
    op.create_table(
        "prompt_clusters",
        sa.Column("scan_id", sa.UUID(), nullable=False),
        sa.Column("cluster_key", sa.String(length=64), nullable=False),
        sa.Column("intent", sa.String(length=64), nullable=False),
        sa.Column("topic", sa.String(length=255), nullable=True),
        sa.Column("service", sa.String(length=255), nullable=True),
        sa.Column("product", sa.String(length=255), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("audience", sa.String(length=255), nullable=True),
        sa.Column("language", sa.String(length=16), nullable=True),
        sa.Column("commercial_intent", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("relevance", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("weight", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column(
            "generation_method", sa.String(length=32), server_default="rule_v1", nullable=False
        ),
        sa.Column("template_version", sa.String(length=32), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["scan_id"],
            ["scans.id"],
            name=op.f("fk_prompt_clusters_scan_id_scans"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prompt_clusters")),
        sa.UniqueConstraint(
            "scan_id", "cluster_key", name=op.f("uq_prompt_clusters_scan_id_cluster_key")
        ),
    )
    op.create_index(
        op.f("ix_prompt_clusters_scan_id"), "prompt_clusters", ["scan_id"], unique=False
    )
    op.create_table(
        "readiness_snapshots",
        sa.Column("scan_id", sa.UUID(), nullable=False),
        sa.Column("overall_score", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("entity_clarity_score", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("offer_clarity_score", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("prompt_coverage_score", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("sourceability_score", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("structured_data_score", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("evidence_trust_score", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("technical_access_score", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("confidence_score", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("methodology_version", sa.String(length=64), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["scan_id"],
            ["scans.id"],
            name=op.f("fk_readiness_snapshots_scan_id_scans"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_readiness_snapshots")),
    )
    op.create_index(
        op.f("ix_readiness_snapshots_scan_id"), "readiness_snapshots", ["scan_id"], unique=False
    )
    op.create_table(
        "reports",
        sa.Column("scan_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column(
            "depth",
            sa.Enum("preview", "full", name="report_depth", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("content_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_reports_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_reports_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["scan_id"], ["scans.id"], name=op.f("fk_reports_scan_id_scans"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reports")),
    )
    op.create_index(
        op.f("ix_reports_organization_id"), "reports", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_reports_project_id"), "reports", ["project_id"], unique=False)
    op.create_index(op.f("ix_reports_scan_id"), "reports", ["scan_id"], unique=False)
    op.create_table(
        "cluster_coverage",
        sa.Column("cluster_id", sa.UUID(), nullable=False),
        sa.Column("coverage_score", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column(
            "matched_requirements_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "missing_requirements_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "supporting_page_ids_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("confidence", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["prompt_clusters.id"],
            name=op.f("fk_cluster_coverage_cluster_id_prompt_clusters"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cluster_coverage")),
        sa.UniqueConstraint("cluster_id", name=op.f("uq_cluster_coverage_cluster_id")),
    )
    op.create_index(
        op.f("ix_cluster_coverage_cluster_id"), "cluster_coverage", ["cluster_id"], unique=False
    )
    op.create_table(
        "cluster_prompts",
        sa.Column("cluster_id", sa.UUID(), nullable=False),
        sa.Column("prompt_key", sa.String(length=64), nullable=False),
        sa.Column("prompt_text", sa.Text(), nullable=False),
        sa.Column("variant_index", sa.Integer(), server_default="0", nullable=False),
        sa.Column("template_id", sa.String(length=64), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["prompt_clusters.id"],
            name=op.f("fk_cluster_prompts_cluster_id_prompt_clusters"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cluster_prompts")),
    )
    op.create_index(
        op.f("ix_cluster_prompts_cluster_id"), "cluster_prompts", ["cluster_id"], unique=False
    )
    op.create_table(
        "evidence",
        sa.Column("scan_id", sa.UUID(), nullable=False),
        sa.Column("page_id", sa.UUID(), nullable=True),
        sa.Column("evidence_type", sa.String(length=64), nullable=False),
        sa.Column("field_name", sa.String(length=128), nullable=False),
        sa.Column("value_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("source_selector", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["page_id"],
            ["crawl_pages.id"],
            name=op.f("fk_evidence_page_id_crawl_pages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["scan_id"], ["scans.id"], name=op.f("fk_evidence_scan_id_scans"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence")),
    )
    op.create_index(op.f("ix_evidence_page_id"), "evidence", ["page_id"], unique=False)
    op.create_index(op.f("ix_evidence_scan_id"), "evidence", ["scan_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_evidence_scan_id"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_page_id"), table_name="evidence")
    op.drop_table("evidence")
    op.drop_index(op.f("ix_cluster_prompts_cluster_id"), table_name="cluster_prompts")
    op.drop_table("cluster_prompts")
    op.drop_index(op.f("ix_cluster_coverage_cluster_id"), table_name="cluster_coverage")
    op.drop_table("cluster_coverage")
    op.drop_index(op.f("ix_reports_scan_id"), table_name="reports")
    op.drop_index(op.f("ix_reports_project_id"), table_name="reports")
    op.drop_index(op.f("ix_reports_organization_id"), table_name="reports")
    op.drop_table("reports")
    op.drop_index(op.f("ix_readiness_snapshots_scan_id"), table_name="readiness_snapshots")
    op.drop_table("readiness_snapshots")
    op.drop_index(op.f("ix_prompt_clusters_scan_id"), table_name="prompt_clusters")
    op.drop_table("prompt_clusters")
    op.drop_index(op.f("ix_payments_scan_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_project_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_organization_id"), table_name="payments")
    op.drop_table("payments")
    op.drop_index(op.f("ix_crawl_pages_scan_id"), table_name="crawl_pages")
    op.drop_index(op.f("ix_crawl_pages_content_hash"), table_name="crawl_pages")
    op.drop_table("crawl_pages")
    op.drop_index(op.f("ix_business_profiles_scan_id"), table_name="business_profiles")
    op.drop_index(op.f("ix_business_profiles_profile_hash"), table_name="business_profiles")
    op.drop_table("business_profiles")
    op.drop_index(op.f("ix_actions_scan_id"), table_name="actions")
    op.drop_table("actions")
    op.drop_index(op.f("ix_scans_project_id"), table_name="scans")
    op.drop_table("scans")
    op.drop_index(op.f("ix_projects_organization_id"), table_name="projects")
    op.drop_table("projects")
    op.drop_index(op.f("ix_organizations_owner_user_id"), table_name="organizations")
    op.drop_table("organizations")
    op.drop_table("users")
    op.drop_table("stripe_events")
    op.drop_index(op.f("ix_jobs_status"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_available_at"), table_name="jobs")
    op.drop_table("jobs")
    # ### end Alembic commands ###
